server:
  port: 8081

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: academiax_super_secret_jwt_key_2026_ps035
  expiration-ms: 3600000
